Update sync.yml

diff --git a/.github/workflows/sync.yml b/.github/workflows/sync.yml
--- a/.github/workflows/sync.yml
+++ b/.github/workflows/sync.yml
@@ -15,21 +15,21 @@ jobs:
 
       - name: Setup Git User Identity
         run: |
-          git config --global user.name 'ma-cyou'
-          git config --global user.email '${{ secrets.EMAIL }}'
+          git config --global user.name "ma-cyou"
+          git config --global user.email "${{ secrets.EMAIL }}"
 
       - name: Push changes to target repositories
         run: |
-          repos=('ma')
-          PAT='${{ secrets.PAT }}'
+          repos=("ma")
+          PAT="${{ secrets.PAT }}"
 
-          for repo in '${repos[@]}'
+          for repo in "${repos[@]}"
           do
             git clone https://${PAT}@github.com/ma-cyou/$repo.git
             cd $repo
 
-            if ! git config --file .gitmodules --get-regexp 'src/lib/shared' > /dev/null; then
-              echo 'Submodule not found. Adding it now.'
+            if ! git config --file .gitmodules --get-regexp "src/lib/shared" > /dev/null; then
+              echo "Submodule not found. Adding it now."
               git submodule add https://github.com/ma-cyou/ma-shared.git src/lib/shared
             fi
 
@@ -37,10 +37,10 @@ jobs:
             
             if [[ -n $(git status --porcelain) ]]; then
               git add src/lib/shared
-              git commit -m 'Update shared components'
-              git push origin main || echo 'Failed to push to $repo'
+              git commit -m "Update shared components"
+              git push origin main || echo "Failed to push to $repo"
             else
-              echo 'No changes to commit in $repo.'
+              echo "No changes to commit in $repo."
             fi
 
             cd ..
