Update sync.yml

diff --git a/.github/workflows/sync.yml b/.github/workflows/sync.yml
--- a/.github/workflows/sync.yml
+++ b/.github/workflows/sync.yml
@@ -21,21 +21,27 @@ jobs:
       - name: Update submodules in target repositories
         run: |
           repos=("ma")
+          PAT="${{ secrets.PAT }}"
 
           for repo in "${repos[@]}"
           do
-            git clone https://${{ secrets.PAT }}@github.com/ma-cyou/$repo.git
+            git clone https://${PAT}@github.com/ma-cyou/$repo.git
             cd $repo
 
             if ! git config --file .gitmodules --get-regexp "src/lib/shared" > /dev/null; then
               echo "Submodule not found. Adding it now."
-              git submodule add https://github.com/ma-cyou/ma-shared.git src/lib/shared
+              git submodule add https://${PAT}@github.com/ma-cyou/ma-shared.git src/lib/shared
             fi
 
             git submodule update --remote src/lib/shared
-            git add src/lib/shared
-            git commit -m "Update shared components"
-            git push origin main
+
+            if [[ -n $(git status --porcelain) ]]; then
+              git add src/lib/shared
+              git commit -m "Update shared components"
+              git push origin main || echo "Failed to push to $repo"
+            else
+              echo "No changes to commit in $repo."
+            fi
 
             cd ..
           done
